# Welcome to Jekyll!

# Theme Settings
minimal_mistakes_skin: "default" # veya istediğiniz bir skin, örneğin "dark"

# Site Settings
locale: "en-US"
title: "Site Title"
description: "An amazing website."
url: "https://abbas-byte.github.io" # GitHub Pages URL'niz
baseurl: "" # Depo isminizden dolayı gerek yok
repository: "abbas-byte/minimal-mistakes" # GitHub username/repo-name
name: "Your Name"
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg" # kendi avatar görüntünüz
  bio: "I am an **amazing** person."
  location: "Somewhere"
  email: "your.email@example.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abbas-byte"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
